---
# hunspell.github.io
# downloads.sourceforge.net/project/wordlist/speller
# wordlist.aspell.net
# github.com/en-wl/wordlist

- apt:
    name: hunspell,libhunspell-dev
  remote_user: root
  when: ansible_os_family == 'Debian'

- homebrew:
    name: hunspell
  when: ansible_system == 'Darwin'

- file:
    path: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}'
    state: directory
  when: hunspell.download_dictionary

- get_url:
    url: 'https://{{ hunspell.mirror }}/project/wordlist/speller/{{ hunspell.version }}/hunspell-en_US-{{ hunspell.version }}.zip'
    dest: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}.zip'
    mode: 0644
  when: ansible_os_family == 'Debian' and hunspell.download_dictionary

- get_url:
    url: 'https://{{ hunspell.mirror }}/project/wordlist/speller/{{ hunspell.version }}/hunspell-en_US-{{ hunspell.version }}.zip'
    dest: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}.zip'
    #client_cert: '{{ ansible_user_dir }}/etc/ssl/cacert.pem'
    # Why this is here: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
    # TODO: Does it work now?
    #validate_certs: no
    mode: 0644
  when: ansible_system == 'Darwin' and hunspell.download_dictionary

- unarchive:
    src: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}.zip'
    dest: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}'
    creates: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}/README_en_US.txt'
    remote_src: yes
  when: hunspell.download_dictionary

- file:
    src: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}'
    dest: '{{ ansible_user_dir }}/tmp/english'
    state: link
  when: hunspell.download_dictionary

- file:
    src: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}/en_US.aff'
    dest: '{{ ansible_user_dir }}/Library/Spelling/en_US.aff'
    state: link
  when: ansible_system == 'Darwin' and hunspell.download_dictionary

- file:
    src: '{{ ansible_user_dir }}/tmp/english-{{ hunspell.version }}/en_US.dic'
    dest: '{{ ansible_user_dir }}/Library/Spelling/en_US.dic'
    state: link
  when: ansible_system == 'Darwin' and hunspell.download_dictionary
